name = "MarkovChains"
uuid = "021c356b-e0a1-4f48-ae7f-990f5eabe724"
authors = ["Michele Fornino <mfornino@mit.edu>"]
version = "0.1.0"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
